### ISSUE TITLE
loading past 20 directories with pushd is ineffective for me

### ISSUE THREAD

**Issue by alusiani** [djoot/all-bash-history#1]
The script https://github.com/djoot/all-bash-history/blob/master/bashrc.user ends with:
` 
( hd 20; pwd ) | while read x; do cd_func "$x"; done
`
That does not work for me. I always get no past directory when typing "dirs" or "cd --" in a new shell. I believe that the above statements cannot possibily work because the "while" construct executes its body in a child shell, and any changes done there (cd_func takes note of the directories with pushd) are discarded.

**Comment by djoot** [comment]
Can you try now? Thanks a bunch! :)

**Comment by alusiani** [comment]
Thanks, with the updated code I get the past directories in the pushd storage ready for "cd --".

I think that a small improvement could also be adding >& /dev/ null as follows
`
    while read x; do cd_func "$x" >&/dev/null ; done <<<"$(hd 20; pwd)"
`
in order to avoid errors being displayed for new shells when some of the past directories were deleted.

**Comment by djoot** [comment]
Made the change, thanks.
